import type { Metadata } from 'next';

import { CategoryItemList } from '@/widgets/CategoryItemList';
import { chosenUsData, ChosenUs } from '@/widgets/company/ChosenUs';
import { InfoConditions } from '@/widgets/company/InfoConditions';

export const metadata: Metadata = {
  title: '1Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <CategoryItemList />
      <ChosenUs data={chosenUsData} />
      <InfoConditions />
    </>
  );
}
